USE gAMSCloud_DEMO_04
GO

IF DB_NAME() <> N'gAMSCloud_DEMO_04' SET NOEXEC ON
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create or alter procedure [dbo].[ASSIGNMENT_WEEKLY_REPORT]
--
GO
PRINT (N'Create or alter procedure [dbo].[ASSIGNMENT_WEEKLY_REPORT]')
GO
CREATE OR ALTER PROCEDURE dbo.ASSIGNMENT_WEEKLY_REPORT @p_TIME_ARRIVE VARCHAR(20) = NULL

AS

BEGIN -- PAGING
    -- PAGING BEGIN
    SELECT 
      a.CAR_ID,
      v.NAME AS 'CAR_NAME',
      a.TIME_ARRIVE,
      DATENAME(WEEKDAY,a.TIME_ARRIVE) AS WEEKDAY,
      GO_TO,
      QUANTITY_TRIP 
    -- SELECT END
    FROM (ASSIGNMENT a
      LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID)
      LEFT JOIN (SELECT AS_ID, GO_TO, QUANTITY_TRIP FROM TRIP WHERE TYPE = '0') T ON a.DisplayedID = T.AS_ID
    WHERE 1 = 1
    AND (DATEDIFF(WEEK,a.TIME_ARRIVE,CONVERT(DATETIME, @p_TIME_ARRIVE, 103)) = 0)
    ORDER BY a.TIME_ARRIVE ASC
  -- PAGING END
END -- PAGING
GO

--
-- Create or alter procedure [dbo].[ASSIGNMENT_Upd]
--
GO
PRINT (N'Create or alter procedure [dbo].[ASSIGNMENT_Upd]')
GO
CREATE OR ALTER PROCEDURE dbo.ASSIGNMENT_Upd @p_DISPLAYEDID VARCHAR(9) = NULL,
@p_LOCATION NVARCHAR(200) = NULL,
@p_POSITION_ID NVARCHAR(15) = NULL,
@p_BROWSING_UNIT NVARCHAR(1) = NULL,
@p_CREATE_DATE VARCHAR(20) = NULL,
@p_FROM_DATE VARCHAR(20) = NULL,
@p_TO_DATE VARCHAR(20) = NULL,
@p_MISSION NVARCHAR(200) = NULL,
@p_MISSION_DETAIL NVARCHAR(200) = NULL,
@p_CAR_ID VARCHAR(15) = NULL,
@p_DRIVER_ID VARCHAR(15) = NULL,
@p_TIME_ARRIVE VARCHAR(20) = NULL,
@p_LOCATION_ARRIVE VARCHAR(15) = NULL,
@p_EMPLOYEE_ID VARCHAR(20) = NULL,
@p_RECORD_STATUS VARCHAR(1) = NULL,
@p_AUTH_STATUS VARCHAR(1) = NULL,
@p_MAKER_ID VARCHAR(15) = NULL,
@p_CREATE_DT VARCHAR(20) = NULL,
@p_CHECKER_ID VARCHAR(15) = NULL,
@p_APPROVE_DT VARCHAR(20) = NULL,
@p_APPROVER_ID VARCHAR(15) = NULL,
@p_BRANCH_ID VARCHAR(15) = NULL,
@p_MO_ID VARCHAR(15) = NULL,
@p_DEP_ID VARCHAR(15) = NULL

AS 
DECLARE @ERRORSYS NVARCHAR(15) = ''
IF (NOT EXISTS (SELECT * FROM ASSIGNMENT a WHERE a.DisplayedID = @p_DISPLAYEDID))
  SET @ERRORSYS = 'NOT FOUND'

IF @ERRORSYS <> ''
BEGIN
	SELECT ErrorCode Result, ErrorDesc ErrorDesc FROM SYS_ERROR WHERE ErrorCode = @ERRORSYS
  RETURN '0'
END

BEGIN TRANSACTION
BEGIN
  UPDATE ASSIGNMENT
  SET LOCATION = @p_LOCATION, POSITION_ID = @p_POSITION_ID, BROWSING_UNIT = @p_BROWSING_UNIT, CREATE_DATE = CONVERT(DATETIME, @p_CREATE_DATE,103), FROM_DATE = CONVERT(DATETIME, @p_FROM_DATE,103), TO_DATE = CONVERT(DATETIME, @p_TO_DATE,103), MISSION = @p_MISSION,
  MISSION_DETAIL = @p_MISSION_DETAIL, CAR_ID = @p_CAR_ID, DRIVER_ID = @p_DRIVER_ID, TIME_ARRIVE = CONVERT(DATETIME, @p_TIME_ARRIVE,103), LOCATION_ARRIVE = @p_LOCATION_ARRIVE, EMPLOYEE_ID = @p_EMPLOYEE_ID,
  RECORD_STATUS = @p_RECORD_STATUS, AUTH_STATUS = @p_AUTH_STATUS, MAKER_ID = @p_MAKER_ID, CREATE_DT = CONVERT(DATETIME, @p_CREATE_DT,103), APPROVE_DT = CONVERT(DATETIME, @p_APPROVE_DT,103),
  APPROVER_ID = @p_APPROVER_ID, BRANCH_ID = @p_BRANCH_ID, MO_ID = @p_MO_ID, DEP_ID = @p_DEP_ID
  WHERE DisplayedID = @p_DISPLAYEDID
END
IF @@Error <> 0 GOTO ABORT
COMMIT TRANSACTION


SELECT '0' AS Result, '' ErrorDesc
RETURN '0'

ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT '-1' AS Result, '' ErrorDesc
    RETURN '-1'
  END

GO

--
-- Create or alter procedure [dbo].[ASSIGNMENT_Search]
--
GO
PRINT (N'Create or alter procedure [dbo].[ASSIGNMENT_Search]')
GO
CREATE OR ALTER PROCEDURE dbo.ASSIGNMENT_Search @p_TOP INT = 500,
@p_BROWSING_UNIT NVARCHAR(10) = NULL,
@p_MISSION NVARCHAR(200) = NULL,
@p_CAR_ID VARCHAR(15) = NULL,
@p_CAR_NAME NVARCHAR(60) = NULL,
@p_DRIVER_ID VARCHAR(15) = NULL,
@p_TIME_ARRIVE VARCHAR(20) = NULL,
@p_LOCATION_ARRIVE VARCHAR(15) = NULL,
@p_EMPLOYEE_ID VARCHAR(20) = NULL,
@p_AUTH_STATUS VARCHAR(1) = NULL,
@p_DISPLAYEDID VARCHAR(9) = NULL,
@p_CREATE_FROM VARCHAR(20) = NULL,
@p_CREATE_TO VARCHAR(20) = NULL,
@p_SEARCH_TYPE VARCHAR(1) = 'A',
@p_DEP_ID VARCHAR(15) = NULL,
@p_IS_ADD VARCHAR(1) = NULL


AS
  BEGIN -- PAGING
    IF (@p_TOP IS NULL OR @p_TOP = '' OR @p_TOP = 0) -- PAGING BEGIN
      SELECT 
      a.*,
      v.NAME AS 'CAR_NAME',
      v.FUEL,
      cd.DEP_NAME,
      cd.DEP_CODE,
      cb.BRANCH_NAME,
      T.GO_FROM,
      T.GO_TO,
      T.GO_TIME,
      T.BACK_TIME,
      e.NAME AS 'DRIVER_NAME',
      e.RANK AS 'DRIVER_RANK',
      e1.NAME AS 'EMPLOYEE_NAME'
      --IIF(a.AUTH_STATUS = '1',N'Ðã duy?t',IIF(a.AUTH_STATUS = '0',N'Ch? duy?t',NULL)) AS AUTH_STATUS
      -- SELECT END
      FROM ASSIGNMENT a
      LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
      LEFT JOIN CM_DEPARTMENT cd ON a.DEP_ID = cd.DEP_ID
      LEFT JOIN CM_BRANCH cb ON a.BRANCH_ID = cb.BRANCH_ID
      LEFT JOIN (SELECT T1.GO_TIME, T2.BACK_TIME, T1.GO_FROM, T1.GO_TO, T1.AS_ID
                FROM (SELECT TIME AS 'GO_TIME', AS_ID, GO_FROM, GO_TO FROM TRIP WHERE TYPE = '0') T1
                LEFT JOIN (SELECT TIME AS 'BACK_TIME', AS_ID FROM TRIP WHERE TYPE = '1') T2 ON T1.AS_ID = T2.AS_ID) T ON a.DisplayedID = T.AS_ID
      LEFT JOIN EMPLOYEEE e ON a.DRIVER_ID = e.DisplayedID
      LEFT JOIN EMPLOYEEE e1 ON a.EMPLOYEE_ID = e1.DisplayedID
      WHERE 1 = 1
      AND (a.BROWSING_UNIT LIKE N'%' + @p_BROWSING_UNIT + N'%' OR @p_BROWSING_UNIT IS NULL OR @p_BROWSING_UNIT = '')
      AND (DATEDIFF(DAY,a.CREATE_DATE, CONVERT(DATETIME,@p_CREATE_FROM,103)) <= 0 OR @p_CREATE_FROM IS NULL OR @p_CREATE_FROM = '')
      AND (DATEDIFF(DAY,a.CREATE_DATE, CONVERT(DATETIME,@p_CREATE_TO,103)) >= 0 OR @p_CREATE_TO IS NULL OR @p_CREATE_TO = '')
      AND (a.MISSION LIKE N'%' + @p_MISSION + N'%' OR @p_MISSION IS NULL OR @p_MISSION = '')
      AND (a.CAR_ID LIKE N'%' + @p_CAR_ID + N'%' OR @p_CAR_ID IS NULL OR @p_CAR_ID = '')
      AND (a.DRIVER_ID LIKE N'%' + @p_DRIVER_ID + N'%' OR @p_DRIVER_ID IS NULL OR @p_DRIVER_ID = '')
      AND (a.LOCATION_ARRIVE LIKE N'%' + @p_LOCATION_ARRIVE + N'%' OR @p_LOCATION_ARRIVE IS NULL OR @p_LOCATION_ARRIVE = '')
      AND (a.EMPLOYEE_ID LIKE N'%' + @p_EMPLOYEE_ID + N'%' OR @p_EMPLOYEE_ID IS NULL OR @p_EMPLOYEE_ID = '')
      AND (a.AUTH_STATUS LIKE N'%' + @p_AUTH_STATUS + N'%' OR @p_AUTH_STATUS IS NULL OR @p_AUTH_STATUS = '')
      AND (a.DISPLAYEDID LIKE N'%' + @p_DISPLAYEDID + N'%' OR @p_DISPLAYEDID IS NULL OR @p_DISPLAYEDID = '')
      AND (@p_IS_ADD IS NULL OR @p_IS_ADD = '0')
      -- PAGING END
    ELSE
      -- PAGING BEGIN 
      SELECT TOP (@p_TOP)
      a.*,
      v.NAME AS 'CAR_NAME',
      v.FUEL,
      cd.DEP_NAME,
      cd.DEP_CODE,
      T.GO_FROM,
      T.GO_TO,
      T.GO_TIME,
      T.BACK_TIME,
      e.NAME AS 'DRIVER_NAME',
      e1.NAME AS 'CONTACT_NAME'
      --IIF(a.AUTH_STATUS = '1',N'Ðã duy?t',IIF(a.AUTH_STATUS = '0',N'Ch? duy?t',NULL)) AS AUTH_STATUS
      -- SELECT END
      FROM ASSIGNMENT a
      LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
      LEFT JOIN CM_DEPARTMENT cd ON a.DEP_ID = cd.DEP_ID
      LEFT JOIN (SELECT T1.GO_TIME, T2.BACK_TIME, T1.GO_FROM, T1.GO_TO, T1.AS_ID
                FROM (SELECT TIME AS 'GO_TIME', AS_ID, GO_FROM, GO_TO FROM TRIP WHERE TYPE = '0') T1
                LEFT JOIN (SELECT TIME AS 'BACK_TIME', AS_ID FROM TRIP WHERE TYPE = '1') T2 ON T1.AS_ID = T2.AS_ID) T ON a.DisplayedID = T.AS_ID
      LEFT JOIN EMPLOYEEE e ON a.DRIVER_ID = e.DisplayedID
      LEFT JOIN EMPLOYEEE e1 ON a.EMPLOYEE_ID = e1.DisplayedID
      WHERE 1 = 1
      AND (a.BROWSING_UNIT LIKE N'%' + @p_BROWSING_UNIT + N'%' OR @p_BROWSING_UNIT IS NULL OR @p_BROWSING_UNIT = '')
      AND (DATEDIFF(DAY,a.CREATE_DATE, CONVERT(DATETIME,@p_CREATE_FROM,103)) <= 0 OR @p_CREATE_FROM IS NULL OR @p_CREATE_FROM = '')
      AND (DATEDIFF(DAY,a.CREATE_DATE, CONVERT(DATETIME,@p_CREATE_TO,103)) >= 0 OR @p_CREATE_TO IS NULL OR @p_CREATE_TO = '')
      AND (a.MISSION LIKE N'%' + @p_MISSION + N'%' OR @p_MISSION IS NULL OR @p_MISSION = '')
      AND (a.CAR_ID LIKE N'%' + @p_CAR_ID + N'%' OR @p_CAR_ID IS NULL OR @p_CAR_ID = '')
      AND (a.DRIVER_ID LIKE N'%' + @p_DRIVER_ID + N'%' OR @p_DRIVER_ID IS NULL OR @p_DRIVER_ID = '')
      AND (a.LOCATION_ARRIVE LIKE N'%' + @p_LOCATION_ARRIVE + N'%' OR @p_LOCATION_ARRIVE IS NULL OR @p_LOCATION_ARRIVE = '')
      AND (a.EMPLOYEE_ID LIKE N'%' + @p_EMPLOYEE_ID + N'%' OR @p_EMPLOYEE_ID IS NULL OR @p_EMPLOYEE_ID = '')
      AND (a.AUTH_STATUS LIKE N'%' + @p_AUTH_STATUS + N'%' OR @p_AUTH_STATUS IS NULL OR @p_AUTH_STATUS = '')
      AND (a.DISPLAYEDID LIKE N'%' + @p_DISPLAYEDID + N'%' OR @p_DISPLAYEDID IS NULL OR @p_DISPLAYEDID = '')
      AND (@p_IS_ADD IS NULL OR @p_IS_ADD = '0')
      -- PAGING END
  END -- PAGING
  --endregion

GO

--
-- Create or alter procedure [dbo].[ASSIGNMENT_REPORT]
--
GO
PRINT (N'Create or alter procedure [dbo].[ASSIGNMENT_REPORT]')
GO
/*
SELECT * FROM ASS_WAREHOUSE_DT
SELECT * FROM TR_PO_MASTER
SELECT * FROM TR_PO_DETAIL
SELECT * FROM ASS_MASTER
SELECT * FROM ASS_ADDNEW
SELECT * FROM ASS_GROUP
[rpt_TSCD_BC016_1] '28-11-2013','DV0001',''
[rpt_TSCD_BC016_1] '21-11-2013'
SELECT * FROM TR_PO_DETAIL
SELECT * FROM CM_GOODS
SELECT * FROM ASS_ADDNEW
*/

/*
REPORT_STATUS:
N - CHUA IN PHIEU
I - DA IN PHIEU XUAT
E - DA IN PHIEU NHAP
F - DA IN PHIEU

I,E SU DUNG TRONG BANG ASS_ADDNEW, TRUONG HOP NHAP VA XUAT

exec [rpt_TSCD_BC016_1] '1/08/2014','dv0001','dv0001','ALL','',''

*/


CREATE OR ALTER PROCEDURE dbo.ASSIGNMENT_REPORT
	@P_TO_DT NVARCHAR(20) = NULL,
	@P_LEVEL varchar(15) = NULL,
	@p_DEP_ID VARCHAR(15) = NULL
AS
BEGIN

SET DATEFORMAT DMY
--T?NG XE
DECLARE @SUM_PLATE decimal(18,0) = (SELECT COUNT(CAR_ID) FROM VEHICLE)
--XE CON
DECLARE @SUM_PLATE_XC decimal(18,0) = (SELECT COUNT(CAR_ID) FROM VEHICLE WHERE CAR_TYPE_ID IN ('CART00000000018','CART00000000019'))
--XE CH? HUY
DECLARE @SUM_PLATE_CH decimal(18,0) = (SELECT COUNT(CAR_ID) FROM VEHICLE WHERE CAR_TYPE_ID = 'CART00000000018')
--XE DU L?CH
DECLARE @SUM_PLATE_DL decimal(18,0) = (SELECT COUNT(CAR_ID) FROM VEHICLE WHERE CAR_TYPE_ID = 'CART00000000019')
--XE V?N T?I
DECLARE @SUM_PLATE_VT decimal(18,0) = (SELECT COUNT(CAR_ID) FROM VEHICLE WHERE CAR_TYPE_ID IN ('CART00000000032','CART00000000033'))
--XE V?N T?I 1
DECLARE @SUM_PLATE_VT1 decimal(18,0) = (SELECT COUNT(CAR_ID) FROM VEHICLE WHERE CAR_TYPE_ID = 'CART00000000032')
--XE V?N T?I 2
DECLARE @SUM_PLATE_VT2 decimal(18,0) = (SELECT COUNT(CAR_ID) FROM VEHICLE WHERE CAR_TYPE_ID = 'CART00000000033')
--XE V?N T?I
DECLARE @SUM_PLATE_CDC decimal(18,0) = (SELECT COUNT(CAR_ID) FROM VEHICLE  WHERE CAR_TYPE_ID IN ('CART00000000021','CART00000000020','CART00000000023'))
--XE CA
DECLARE @SUM_PLATE_C decimal(18,0) = (SELECT COUNT(CAR_ID) FROM VEHICLE WHERE CAR_TYPE_ID = 'CART00000000021')
--XE C?U THUONG
DECLARE @SUM_PLATE_CT decimal(18,0) = (SELECT COUNT(CAR_ID) FROM VEHICLE WHERE CAR_TYPE_ID = 'CART00000000020')
--XE C?U H?A
DECLARE @SUM_PLATE_CF decimal(18,2) = (SELECT COUNT(CAR_ID) FROM VEHICLE WHERE CAR_TYPE_ID = 'CART00000000023')
--XE KHÔNG HO?T Ð?NG
--DECLARE @SUM_PLATE_KHD decimal(18,2) = (SELECT COUNT(v.CAR_ID) 
--											FROM VEHICLE v
--											LEFT JOIN CM_ALLCODE C ON C.CDVAL = A.ACTIVE_STATUS AND CDNAME = 'ACTIVE_STATUS'
--											WHERE A.ACTIVE_STATUS <> 'HoatDong' AND A.AUTH_STATUS = 'A')
--MÁY PHÁT ÐI?N
--DECLARE @SUM_PLATE_PD decimal(18,2) = (SELECT COUNT(CAR_ID) FROM CAR_MASTER WHERE AUTH_STATUS = 'A' AND CAR_TYPE_ID = 'CART00000000035')
--
DECLARE @CAR_ID VARCHAR(20), @CAR_TYPE_MODEL NVARCHAR(200), @CONSUMPTION decimal(18,2)
DECLARE @D INT = 0

declare @tmp table(
	STT INT,
	CAR_TYPE_MODEL NVARCHAR(200),
	CAR_ID VARCHAR(20),
	CONSUMPTION decimal(18, 2),
	SUM_NUM_KM_START decimal(18, 2),
	SUM_NUM_KM_END decimal(18, 2),
	SUM_NUM_KM decimal(18, 2),
	SUM_NUM_KM_CAR_ASSIGN decimal(18, 2),
	DIFF_KM decimal(18, 2),
	SUM_TRIP_NUMBER decimal(18, 2),
	GASOLINE decimal(18, 2),
	OIL decimal(18, 2),
	GREASE_OIL decimal(18, 2),
	NOTES NVARCHAR(1000)
)


insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'Ô TÔ',@SUM_PLATE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'XE CON',@SUM_PLATE_XC,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'XE CH? HUY',@SUM_PLATE_CH,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

	--INSERT XE CH? HUY
	DECLARE cursorCar_CH CURSOR FOR
		SELECT A.CAR_ID, (B.CAR_TYPE_NAME + ' ' + (CASE WHEN A.NAME IS NULL THEN '' ELSE A.NAME END)) AS CAR_TYPE_MODEL, A.CONSUMPTION  
		FROM VEHICLE A 
		LEFT JOIN CAR_TYPE B ON B.CAR_TYPE_ID = A.CAR_TYPE_ID
		WHERE A.CAR_TYPE_ID = 'CART00000000018'
		
		Open cursorCar_CH

		FETCH NEXT FROM cursorCar_CH INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		WHILE @@FETCH_STATUS = 0
		BEGIN			
			SET @D = @D+1;
			insert into @tmp SELECT @D AS STT,@CAR_TYPE_MODEL AS CAR_TYPE_MODEL, @CAR_ID AS CAR_ID, @CONSUMPTION AS CONSUMPTION, NULL AS SUM_NUM_KM_START, NULL AS SUM_NUM_KM_START,
				NULL AS SUM_NUM_KM, ISNULL(sum(T.SUM_LENGTH),0) AS SUM_NUM_KM_CAR_ASSIGN, NULL AS DIFF_KM, ISNULL(sum(T.SUM_TRIP),0) AS SUM_TRIP_NUMBER, 
				ISNULL(SUM(X.SUMX),0) AS GASOLINE, ISNULL(SUM(D.SUMX),0) AS OIL, ISNULL(SUM(M.SUMX),0) AS GREASE_OIL, NULL AS NOTES 
			FROM ASSIGNMENT a
			LEFT JOIN (SELECT t.AS_ID, SUM(t.LENGTH) AS SUM_LENGTH, SUM(t.QUANTITY_TRIP) AS SUM_TRIP FROM TRIP t GROUP BY t.AS_ID) AS T ON a.DisplayedID = T.AS_ID -------------------------------- QUANTITY_TRIP AND KM
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 2
				AND v.CAR_TYPE_ID = 'CART00000000018' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS X ON X.DisplayedID =  a.DisplayedID --=ASSIGNMENT.DISPLAYEDID ------- FUEL
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 1
				AND v.CAR_TYPE_ID = 'CART00000000018' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS M ON M.DisplayedID = a.DisplayedID ------------------ GREASE
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 3
				AND v.CAR_TYPE_ID = 'CART00000000018' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS D ON D.DisplayedID = a.DisplayedID ------------------- OIL
      LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
			LEFT JOIN CAR_TYPE CT ON CT.CAR_TYPE_ID = v.CAR_TYPE_ID
			WHERE 1=1 
			--AND B.AUTH_STATUS = 'A'
			AND v.CAR_TYPE_ID = 'CART00000000018' AND a.CAR_ID = @CAR_ID
			AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
			OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
			AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT)) 


			FETCH NEXT FROM cursorCar_CH INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		END
	
		CLOSE cursorCar_CH
		DEALLOCATE cursorCar_CH

	--INSERT XE DU L?CH
insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'XE DU L?CH',@SUM_PLATE_DL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

	DECLARE cursorCar_DL CURSOR FOR
		SELECT A.CAR_ID, (B.CAR_TYPE_NAME + ' ' + (CASE WHEN A.NAME IS NULL THEN '' ELSE A.NAME END)) AS CAR_TYPE_MODEL, A.CONSUMPTION  
		FROM VEHICLE A 
		LEFT JOIN CAR_TYPE B ON B.CAR_TYPE_ID = A.CAR_TYPE_ID
		WHERE A.CAR_TYPE_ID = 'CART00000000019'
		Open cursorCar_DL

		FETCH NEXT FROM cursorCar_DL INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		WHILE @@FETCH_STATUS = 0
		BEGIN			
			SET @D = @D+1;
			insert into @tmp SELECT @D AS STT,@CAR_TYPE_MODEL AS CAR_TYPE_MODEL, @CAR_ID AS CAR_ID, @CONSUMPTION AS CONSUMPTION, NULL AS SUM_NUM_KM_START, NULL AS SUM_NUM_KM_START,
				NULL AS SUM_NUM_KM, ISNULL(sum(T.SUM_LENGTH),0) AS SUM_NUM_KM_CAR_ASSIGN, NULL AS DIFF_KM, ISNULL(sum(T.SUM_TRIP),0) AS SUM_TRIP_NUMBER, 
				ISNULL(SUM(X.SUMX),0) AS GASOLINE, ISNULL(SUM(D.SUMX),0) AS OIL, ISNULL(SUM(M.SUMX),0) AS GREASE_OIL, NULL AS NOTES 
			FROM ASSIGNMENT a
			LEFT JOIN (SELECT t.AS_ID, SUM(t.LENGTH) AS SUM_LENGTH, SUM(t.QUANTITY_TRIP) AS SUM_TRIP FROM TRIP t GROUP BY t.AS_ID) AS T ON a.DisplayedID = T.AS_ID -------------------------------- QUANTITY_TRIP AND KM
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 2
				AND v.CAR_TYPE_ID = 'CART00000000019' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS X ON X.DisplayedID =  a.DisplayedID --=ASSIGNMENT.DISPLAYEDID ------- FUEL
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 1
				AND v.CAR_TYPE_ID = 'CART00000000019' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS M ON M.DisplayedID = a.DisplayedID ------------------ GREASE
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 3
				AND v.CAR_TYPE_ID = 'CART00000000019' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS D ON D.DisplayedID = a.DisplayedID ------------------- OIL
      LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
			LEFT JOIN CAR_TYPE CT ON CT.CAR_TYPE_ID = v.CAR_TYPE_ID
			WHERE 1=1 
			--AND B.AUTH_STATUS = 'A'
			AND v.CAR_TYPE_ID = 'CART00000000019' AND a.CAR_ID = @CAR_ID
			AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
			OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
			AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT)) 

			FETCH NEXT FROM cursorCar_DL INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		END
	
		CLOSE cursorCar_DL
		DEALLOCATE cursorCar_DL

	--XE V?N T?I 
insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'XE V?N T?I',@SUM_PLATE_VT,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

	--INSERT XE V?N T?I 1 C?U
insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'XE V?N T?I 1 C?U',@SUM_PLATE_VT1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

	DECLARE cursorCar_VT1 CURSOR FOR
		SELECT A.CAR_ID, (B.CAR_TYPE_NAME + ' ' + (CASE WHEN A.NAME IS NULL THEN '' ELSE A.NAME END)) AS CAR_TYPE_MODEL, A.CONSUMPTION  
		FROM VEHICLE A 
		LEFT JOIN CAR_TYPE B ON B.CAR_TYPE_ID = A.CAR_TYPE_ID
		WHERE A.CAR_TYPE_ID = 'CART00000000032'
		
		Open cursorCar_VT1

		FETCH NEXT FROM cursorCar_VT1 INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		WHILE @@FETCH_STATUS = 0
		BEGIN			
			SET @D = @D+1;
			insert into @tmp SELECT @D AS STT,@CAR_TYPE_MODEL AS CAR_TYPE_MODEL, @CAR_ID AS CAR_ID, @CONSUMPTION AS CONSUMPTION, NULL AS SUM_NUM_KM_START, NULL AS SUM_NUM_KM_START,
				NULL AS SUM_NUM_KM, ISNULL(sum(T.SUM_LENGTH),0) AS SUM_NUM_KM_CAR_ASSIGN, NULL AS DIFF_KM, ISNULL(sum(T.SUM_TRIP),0) AS SUM_TRIP_NUMBER, 
				ISNULL(SUM(X.SUMX),0) AS GASOLINE, ISNULL(SUM(D.SUMX),0) AS OIL, ISNULL(SUM(M.SUMX),0) AS GREASE_OIL, NULL AS NOTES 
			FROM ASSIGNMENT a
			LEFT JOIN (SELECT t.AS_ID, SUM(t.LENGTH) AS SUM_LENGTH, SUM(t.QUANTITY_TRIP) AS SUM_TRIP FROM TRIP t GROUP BY t.AS_ID) AS T ON a.DisplayedID = T.AS_ID -------------------------------- QUANTITY_TRIP AND KM
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 2
				AND v.CAR_TYPE_ID = 'CART00000000032' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS X ON X.DisplayedID =  a.DisplayedID --=ASSIGNMENT.DISPLAYEDID ------- FUEL
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 1
				AND v.CAR_TYPE_ID = 'CART00000000032' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS M ON M.DisplayedID = a.DisplayedID ------------------ GREASE
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 3
				AND v.CAR_TYPE_ID = 'CART00000000032' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS D ON D.DisplayedID = a.DisplayedID ------------------- OIL
      LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
			LEFT JOIN CAR_TYPE CT ON CT.CAR_TYPE_ID = v.CAR_TYPE_ID
			WHERE 1=1 
			--AND B.AUTH_STATUS = 'A'
			AND v.CAR_TYPE_ID = 'CART00000000032' AND a.CAR_ID = @CAR_ID
			AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
			OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
			AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT)) 

			FETCH NEXT FROM cursorCar_VT1 INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		END
	
		CLOSE cursorCar_VT1
		DEALLOCATE cursorCar_VT1

	--INSERT XE V?N T?I 2 C?U
insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'XE V?N T?I 2 C?U',@SUM_PLATE_VT2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

	DECLARE cursorCar_VT2 CURSOR FOR
		SELECT A.CAR_ID, (B.CAR_TYPE_NAME + ' ' + (CASE WHEN A.NAME IS NULL THEN '' ELSE A.NAME END)) AS CAR_TYPE_MODEL, A.CONSUMPTION  
		FROM VEHICLE A 
		LEFT JOIN CAR_TYPE B ON B.CAR_TYPE_ID = A.CAR_TYPE_ID
		WHERE A.CAR_TYPE_ID = 'CART00000000033'
		
		Open cursorCar_VT2

		FETCH NEXT FROM cursorCar_VT2 INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		WHILE @@FETCH_STATUS = 0
		BEGIN			
			SET @D = @D+1;
			insert into @tmp SELECT @D AS STT,@CAR_TYPE_MODEL AS CAR_TYPE_MODEL, @CAR_ID AS CAR_ID, @CONSUMPTION AS CONSUMPTION, NULL AS SUM_NUM_KM_START, NULL AS SUM_NUM_KM_START,
				NULL AS SUM_NUM_KM, ISNULL(sum(T.SUM_LENGTH),0) AS SUM_NUM_KM_CAR_ASSIGN, NULL AS DIFF_KM, ISNULL(sum(T.SUM_TRIP),0) AS SUM_TRIP_NUMBER, 
				ISNULL(SUM(X.SUMX),0) AS GASOLINE, ISNULL(SUM(D.SUMX),0) AS OIL, ISNULL(SUM(M.SUMX),0) AS GREASE_OIL, NULL AS NOTES 
			FROM ASSIGNMENT a
			LEFT JOIN (SELECT t.AS_ID, SUM(t.LENGTH) AS SUM_LENGTH, SUM(t.QUANTITY_TRIP) AS SUM_TRIP FROM TRIP t GROUP BY t.AS_ID) AS T ON a.DisplayedID = T.AS_ID -------------------------------- QUANTITY_TRIP AND KM
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 2
				AND v.CAR_TYPE_ID = 'CART00000000033' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS X ON X.DisplayedID =  a.DisplayedID --=ASSIGNMENT.DISPLAYEDID ------- FUEL
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 1
				AND v.CAR_TYPE_ID = 'CART00000000033' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS M ON M.DisplayedID = a.DisplayedID ------------------ GREASE
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 3
				AND v.CAR_TYPE_ID = 'CART00000000033' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS D ON D.DisplayedID = a.DisplayedID ------------------- OIL
      LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
			LEFT JOIN CAR_TYPE CT ON CT.CAR_TYPE_ID = v.CAR_TYPE_ID
			WHERE 1=1 
			--AND B.AUTH_STATUS = 'A'
			AND v.CAR_TYPE_ID = 'CART00000000033' AND a.CAR_ID = @CAR_ID
			AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
			OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
			AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT)) 

			FETCH NEXT FROM cursorCar_VT2 INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		END
	
		CLOSE cursorCar_VT2
		DEALLOCATE cursorCar_VT2

	--INSERT XE CHUYÊN DÙNG CHUNG
insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'XE CHUYÊN DÙNG CHUNG',@SUM_PLATE_CDC,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

	--INSERT XE CA
insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'XE CA',@SUM_PLATE_C,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

	DECLARE cursorCar_C CURSOR FOR
		SELECT A.CAR_ID, (B.CAR_TYPE_NAME + ' ' + (CASE WHEN A.NAME IS NULL THEN '' ELSE A.NAME END)) AS CAR_TYPE_MODEL, A.CONSUMPTION  
		FROM VEHICLE A 
		LEFT JOIN CAR_TYPE B ON B.CAR_TYPE_ID = A.CAR_TYPE_ID
		WHERE A.CAR_TYPE_ID = 'CART00000000021'
		
		Open cursorCar_C

		FETCH NEXT FROM cursorCar_C INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		WHILE @@FETCH_STATUS = 0
		BEGIN			
			SET @D = @D+1;
			insert into @tmp SELECT @D AS STT,@CAR_TYPE_MODEL AS CAR_TYPE_MODEL, @CAR_ID AS CAR_ID, @CONSUMPTION AS CONSUMPTION, NULL AS SUM_NUM_KM_START, NULL AS SUM_NUM_KM_START,
				NULL AS SUM_NUM_KM, ISNULL(sum(T.SUM_LENGTH),0) AS SUM_NUM_KM_CAR_ASSIGN, NULL AS DIFF_KM, ISNULL(sum(T.SUM_TRIP),0) AS SUM_TRIP_NUMBER, 
				ISNULL(SUM(X.SUMX),0) AS GASOLINE, ISNULL(SUM(D.SUMX),0) AS OIL, ISNULL(SUM(M.SUMX),0) AS GREASE_OIL, NULL AS NOTES 
			FROM ASSIGNMENT a
			LEFT JOIN (SELECT t.AS_ID, SUM(t.LENGTH) AS SUM_LENGTH, SUM(t.QUANTITY_TRIP) AS SUM_TRIP FROM TRIP t GROUP BY t.AS_ID) AS T ON a.DisplayedID = T.AS_ID -------------------------------- QUANTITY_TRIP AND KM
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 2
				AND v.CAR_TYPE_ID = 'CART00000000021' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS X ON X.DisplayedID =  a.DisplayedID --=ASSIGNMENT.DISPLAYEDID ------- FUEL
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 1
				AND v.CAR_TYPE_ID = 'CART00000000021' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS M ON M.DisplayedID = a.DisplayedID ------------------ GREASE
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 3
				AND v.CAR_TYPE_ID = 'CART00000000021' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS D ON D.DisplayedID = a.DisplayedID ------------------- OIL
      LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
			LEFT JOIN CAR_TYPE CT ON CT.CAR_TYPE_ID = v.CAR_TYPE_ID
			WHERE 1=1 
			--AND B.AUTH_STATUS = 'A'
			AND v.CAR_TYPE_ID = 'CART00000000021' AND a.CAR_ID = @CAR_ID
			AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
			OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
			AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT)) 

			FETCH NEXT FROM cursorCar_C INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		END
	
		CLOSE cursorCar_C
		DEALLOCATE cursorCar_C

		--INSERT XE C?U THUONG
insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'XE C?U THUONG',@SUM_PLATE_CT,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

	DECLARE cursorCar_CT CURSOR FOR
		SELECT A.CAR_ID, (B.CAR_TYPE_NAME + ' ' + (CASE WHEN A.NAME IS NULL THEN '' ELSE A.NAME END)) AS CAR_TYPE_MODEL, A.CONSUMPTION  
		FROM VEHICLE A 
		LEFT JOIN CAR_TYPE B ON B.CAR_TYPE_ID = A.CAR_TYPE_ID
		WHERE A.CAR_TYPE_ID = 'CART00000000020'
		
		Open cursorCar_CT

		FETCH NEXT FROM cursorCar_CT INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		WHILE @@FETCH_STATUS = 0
		BEGIN			
			SET @D = @D+1;
			insert into @tmp SELECT @D AS STT,@CAR_TYPE_MODEL AS CAR_TYPE_MODEL, @CAR_ID AS CAR_ID, @CONSUMPTION AS CONSUMPTION, NULL AS SUM_NUM_KM_START, NULL AS SUM_NUM_KM_START,
				NULL AS SUM_NUM_KM, ISNULL(sum(T.SUM_LENGTH),0) AS SUM_NUM_KM_CAR_ASSIGN, NULL AS DIFF_KM, ISNULL(sum(T.SUM_TRIP),0) AS SUM_TRIP_NUMBER, 
				ISNULL(SUM(X.SUMX),0) AS GASOLINE, ISNULL(SUM(D.SUMX),0) AS OIL, ISNULL(SUM(M.SUMX),0) AS GREASE_OIL, NULL AS NOTES 
			FROM ASSIGNMENT a
			LEFT JOIN (SELECT t.AS_ID, SUM(t.LENGTH) AS SUM_LENGTH, SUM(t.QUANTITY_TRIP) AS SUM_TRIP FROM TRIP t GROUP BY t.AS_ID) AS T ON a.DisplayedID = T.AS_ID -------------------------------- QUANTITY_TRIP AND KM
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 2
				AND v.CAR_TYPE_ID = 'CART00000000020' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS X ON X.DisplayedID =  a.DisplayedID --=ASSIGNMENT.DISPLAYEDID ------- FUEL
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 1
				AND v.CAR_TYPE_ID = 'CART00000000020' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS M ON M.DisplayedID = a.DisplayedID ------------------ GREASE
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 3
				AND v.CAR_TYPE_ID = 'CART00000000020' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS D ON D.DisplayedID = a.DisplayedID ------------------- OIL
      LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
			LEFT JOIN CAR_TYPE CT ON CT.CAR_TYPE_ID = v.CAR_TYPE_ID
			WHERE 1=1 
			--AND B.AUTH_STATUS = 'A'
			AND v.CAR_TYPE_ID = 'CART00000000020' AND a.CAR_ID = @CAR_ID
			AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
			OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
			AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT)) 

			FETCH NEXT FROM cursorCar_CT INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		END
	
		CLOSE cursorCar_CT
		DEALLOCATE cursorCar_CT

		--INSERT XE C?U H?A
insert into @tmp(STT,CAR_TYPE_MODEL,CAR_ID,CONSUMPTION,SUM_NUM_KM_START,SUM_NUM_KM_END,SUM_NUM_KM,SUM_NUM_KM_CAR_ASSIGN,DIFF_KM,
	SUM_TRIP_NUMBER,GASOLINE,OIL,GREASE_OIL,NOTES) VALUES(NULL,N'XE C?U H?A',@SUM_PLATE_CF,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

	DECLARE cursorCar_CF CURSOR FOR
		SELECT A.CAR_ID, (B.CAR_TYPE_NAME + ' ' + (CASE WHEN A.NAME IS NULL THEN '' ELSE A.NAME END)) AS CAR_TYPE_MODEL, A.CONSUMPTION  
		FROM VEHICLE A 
		LEFT JOIN CAR_TYPE B ON B.CAR_TYPE_ID = A.CAR_TYPE_ID
		WHERE A.CAR_TYPE_ID = 'CART00000000023'
		
		Open cursorCar_CF

		FETCH NEXT FROM cursorCar_CF INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		WHILE @@FETCH_STATUS = 0
		BEGIN			
			SET @D = @D+1;
			insert into @tmp SELECT @D AS STT,@CAR_TYPE_MODEL AS CAR_TYPE_MODEL, @CAR_ID AS CAR_ID, @CONSUMPTION AS CONSUMPTION, NULL AS SUM_NUM_KM_START, NULL AS SUM_NUM_KM_START,
				NULL AS SUM_NUM_KM, ISNULL(sum(T.SUM_LENGTH),0) AS SUM_NUM_KM_CAR_ASSIGN, NULL AS DIFF_KM, ISNULL(sum(T.SUM_TRIP),0) AS SUM_TRIP_NUMBER, 
				ISNULL(SUM(X.SUMX),0) AS GASOLINE, ISNULL(SUM(D.SUMX),0) AS OIL, ISNULL(SUM(M.SUMX),0) AS GREASE_OIL, NULL AS NOTES 
			FROM ASSIGNMENT a
			LEFT JOIN (SELECT t.AS_ID, SUM(t.LENGTH) AS SUM_LENGTH, SUM(t.QUANTITY_TRIP) AS SUM_TRIP FROM TRIP t GROUP BY t.AS_ID) AS T ON a.DisplayedID = T.AS_ID -------------------------------- QUANTITY_TRIP AND KM
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 2
				AND v.CAR_TYPE_ID = 'CART00000000023' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS X ON X.DisplayedID =  a.DisplayedID --=ASSIGNMENT.DISPLAYEDID ------- FUEL
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 1
				AND v.CAR_TYPE_ID = 'CART00000000023' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS M ON M.DisplayedID = a.DisplayedID ------------------ GREASE
			LEFT JOIN 
			(SELECT a.DisplayedID,SUM(af.CONSUMPTION) AS SUMX FROM ASSIGNMENT a
        LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
				LEFT JOIN ASSIGNMENT_FUEL af ON af.AS_ID = a.DisplayedID
				LEFT JOIN CM_ALLCODE CA ON CA.CDVAL = af.FUEL_ID
				WHERE 1=1
				AND CA.CDNAME = 'FUELSTYPE'
				AND CA.LSTODR = 3
				AND v.CAR_TYPE_ID = 'CART00000000023' AND v.CAR_ID = @CAR_ID
				AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
				OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
				AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT))
				GROUP BY a.DisplayedID
			) AS D ON D.DisplayedID = a.DisplayedID ------------------- OIL
      LEFT JOIN VEHICLE v ON a.CAR_ID = v.CAR_ID
			LEFT JOIN CAR_TYPE CT ON CT.CAR_TYPE_ID = v.CAR_TYPE_ID
			WHERE 1=1 
			--AND B.AUTH_STATUS = 'A'
			AND v.CAR_TYPE_ID = 'CART00000000023' AND a.CAR_ID = @CAR_ID
			AND ((@P_LEVEL = 'ALL' and a.DEP_ID in (select DEP_ID from CM_DEPARTMENT))
			OR (@P_LEVEL = 'UNIT' and a.DEP_ID = @p_DEP_ID) or @p_DEP_ID = '' or @p_DEP_ID is null)
			AND (MONTH(a.TIME_ARRIVE)=MONTH(@P_TO_DT) AND YEAR(a.TIME_ARRIVE) = YEAR(@P_TO_DT)) 

			FETCH NEXT FROM cursorCar_CF INTO @CAR_ID,@CAR_TYPE_MODEL,@CONSUMPTION	
		END
	
		CLOSE cursorCar_CF
		DEALLOCATE cursorCar_CF

	SELECT * FROM @tmp



END
GO

--
-- Create or alter procedure [dbo].[ASSIGNMENT_INS]
--
GO
PRINT (N'Create or alter procedure [dbo].[ASSIGNMENT_INS]')
GO
CREATE OR ALTER PROCEDURE dbo.ASSIGNMENT_INS
@p_AS_ID NVARCHAR(20) = NULL,
@p_LOCATION NVARCHAR(200) = NULL,
@p_POSITION_ID NVARCHAR(15) = NULL,
@p_BROWSING_UNIT NVARCHAR(1) = NULL,
@p_CREATE_DATE VARCHAR(20) = NULL,
@p_FROM_DATE VARCHAR(20) = NULL,
@p_TO_DATE VARCHAR(20) = NULL,
@p_MISSION NVARCHAR(200) = NULL,
@p_MISSION_DETAIL NVARCHAR(200) = NULL,
@p_CAR_ID VARCHAR(15) = NULL,
@p_DRIVER_ID VARCHAR(15) = NULL,
@p_TIME_ARRIVE VARCHAR(20) = NULL,
@p_LOCATION_ARRIVE VARCHAR(15) = NULL,
@p_EMPLOYEE_ID VARCHAR(20) = NULL,
@p_RECORD_STATUS VARCHAR(1) = NULL,
@p_AUTH_STATUS VARCHAR(1) = NULL,
@p_MAKER_ID VARCHAR(15) = NULL,
@p_CREATE_DT VARCHAR(20) = NULL,
@p_CHECKER_ID VARCHAR(15) = NULL,
@p_APPROVE_DT VARCHAR(20) = NULL,
@p_APPROVER_ID VARCHAR(15) = NULL,
@p_BRANCH_ID VARCHAR(15) = NULL,
@p_MO_ID VARCHAR(15) = NULL,
@p_DEP_ID VARCHAR(15) = NULL


AS

  IF @p_CREATE_DATE IS NULL OR @p_CREATE_DATE = '' SET @p_CREATE_DATE = GETDATE()
  ELSE SET @p_CREATE_DATE = CONVERT(DATETIME, @p_CREATE_DATE, 103);
  SET @p_FROM_DATE = CONVERT(DATETIME, @p_FROM_DATE, 103)
  SET @p_TO_DATE = CONVERT(DATETIME, @p_TO_DATE, 103)
  SET @p_TIME_ARRIVE = CONVERT(DATETIME, @p_TIME_ARRIVE, 103)
  SET @p_CREATE_DT = CONVERT(DATETIME, @p_CREATE_DT, 103)
  SET @p_APPROVE_DT = CONVERT(DATETIME, @p_APPROVE_DT, 103)

  DECLARE  @p_INYEAR_ID INT = -1;
  IF (SELECT MAX(INYEAR_ID) FROM ASSIGNMENT WHERE YEAR(CREATE_DATE) = YEAR(@p_CREATE_DATE)) IS NOT NULL
  SET @p_INYEAR_ID =  (SELECT MAX(INYEAR_ID) FROM ASSIGNMENT WHERE YEAR(CREATE_DATE) = YEAR(@p_CREATE_DATE)) + 1;
  ELSE SET @p_INYEAR_ID = 0;


  BEGIN TRANSACTION
  INSERT INTO [ASSIGNMENT]([LOCATION],[POSITION_ID],[BROWSING_UNIT],[CREATE_DATE],[FROM_DATE],[TO_DATE],[MISSION],[MISSION_DETAIL],[CAR_ID],[DRIVER_ID],[TIME_ARRIVE],[LOCATION_ARRIVE],[EMPLOYEE_ID],[RECORD_STATUS],[AUTH_STATUS],[MAKER_ID],[CREATE_DT],[CHECKER_ID],[APPROVE_DT],[APPROVER_ID],[BRANCH_ID],[MO_ID],[DEP_ID],[INYEAR_ID]) 
  VALUES (@p_LOCATION,@p_POSITION_ID,@p_BROWSING_UNIT,convert(DATETIME, @p_CREATE_DATE,103),convert(DATETIME, @p_FROM_DATE,103),CONVERT(DATETIME, @p_TO_DATE,103),@p_MISSION,@p_MISSION_DETAIL,@p_CAR_ID,@p_DRIVER_ID,convert(DATETIME, @p_TIME_ARRIVE,103),@p_LOCATION_ARRIVE,@p_EMPLOYEE_ID,@p_RECORD_STATUS,@p_AUTH_STATUS,@p_MAKER_ID,convert(DATETIME, @p_CREATE_DT,103),@p_CHECKER_ID,@p_APPROVE_DT,@p_APPROVER_ID,@p_BRANCH_ID,@p_MO_ID,@p_DEP_ID,@p_INYEAR_ID)
  IF @@Error <> 0 GOTO ABORT
  COMMIT TRANSACTION

  SELECT
  '0' AS RESULT, IDENT_CURRENT('ASSIGNMENT') AS_ID
  RETURN '0'

ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT
      '-1' AS Result
     ,'' ID
    RETURN '-1'
  END
GO

--
-- Create or alter procedure [dbo].[ASSIGNMENT_DEL]
--
GO
PRINT (N'Create or alter procedure [dbo].[ASSIGNMENT_DEL]')
GO
CREATE OR ALTER PROCEDURE dbo.ASSIGNMENT_DEL @p_DISPLAYEDID VARCHAR(9) = NULL
AS 
DECLARE @ERRORSYS NVARCHAR(15) = ''
IF (NOT EXISTS (SELECT * FROM ASSIGNMENT a WHERE a.DisplayedID = @p_DISPLAYEDID))
  SET @ERRORSYS = 'NOT FOUND'

IF @ERRORSYS <> ''
BEGIN
	SELECT ErrorCode Result, ErrorDesc ErrorDesc FROM SYS_ERROR WHERE ErrorCode = @ERRORSYS
  RETURN '0'
END

BEGIN TRANSACTION
BEGIN
  DELETE FROM ASSIGNMENT WHERE DisplayedID = @p_DISPLAYEDID
  IF @@error <> 0
  GOTO ABORT
END
COMMIT TRANSACTION

SELECT '0' AS Result, '' ErrorDesc
RETURN '0'

ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT '-1' AS Result, '' ErrorDesc
    RETURN '-1'
  END

GO