CREATE PROCEDURE dbo.ASSIGNMENT_Search @p_TOP INT = 500,
@p_AS_ID NVARCHAR(20) = NULL,
@p_LOCATION NVARCHAR(200) = NULL,
@p_POSITION_ID NVARCHAR(15) = NULL,
@p_BROWSING_UNIT NVARCHAR(1) = NULL,
@p_CREATE_DATE VARCHAR(20) = NULL,
@p_FROM_DATE VARCHAR(20) = NULL,
@p_TO_DATE VARCHAR(20) = NULL,
@p_MISSION NVARCHAR(200) = NULL,
@p_MISSION_DETAIL NVARCHAR(200) = NULL,
@p_CAR_ID VARCHAR(15) = NULL,
@p_DRIVER_ID VARCHAR(15) = NULL,
@p_TIME_ARRIVE VARCHAR(20) = NULL,
@p_LOCATION_ARRIVE VARCHAR(15) = NULL,
@p_EMPLOYEE_ID VARCHAR(20) = NULL,
@p_RECORD_STATUS VARCHAR(1) = NULL,
@p_AUTH_STATUS VARCHAR(1) = NULL,
@p_MAKER_ID VARCHAR(15) = NULL,
@p_CREATE_DT VARCHAR(20) = NULL,
@p_CHECKER_ID VARCHAR(15) = NULL,
@p_APPROVE_DT VARCHAR(20) = NULL,
@p_APPROVER_ID VARCHAR(15) = NULL,
@p_BRANCH_ID VARCHAR(15) = NULL,
@p_MO_ID VARCHAR(15) = NULL,
@p_DEP_ID VARCHAR(15) = NULL,
@p_INYEAR_ID INT = NULL,
@p_DISPLAYEDID VARCHAR(9) = NULL

AS
  BEGIN -- PAGING
    IF (@p_TOP IS NULL OR @p_TOP = '' OR @p_TOP = 0) -- PAGING BEGIN
      SELECT a.*
      -- SELECT END
      FROM ASSIGNMENT a WHERE 1 = 1
      AND (a.LOCATION LIKE N'%' + @p_LOCATION + N'%' OR @p_LOCATION IS NULL OR @p_LOCATION = '')
      AND (a.POSITION_ID LIKE N'%' + @p_POSITION_ID + N'%' OR @p_POSITION_ID IS NULL OR @p_POSITION_ID = '')
      AND (a.BROWSING_UNIT LIKE N'%' + @p_BROWSING_UNIT + N'%' OR @p_BROWSING_UNIT IS NULL OR @p_BROWSING_UNIT = '')
      AND (DATEDIFF(DAY,a.CREATE_DATE, CONVERT(DATETIME,@p_CREATE_DATE,103)) = 0 OR @p_CREATE_DATE IS NULL OR @p_CREATE_DATE = '')
      AND (DATEDIFF(DAY,a.FROM_DATE, CONVERT(DATETIME, @p_FROM_DATE,103)) = 0 OR @p_FROM_DATE IS NULL OR @p_FROM_DATE = '')
      AND (DATEDIFF(DAY,a.TO_DATE, CONVERT(DATETIME, @p_TO_DATE,103)) = 0 OR @p_TO_DATE IS NULL OR @p_TO_DATE = '')
      AND (a.MISSION LIKE N'%' + @p_MISSION + N'%' OR @p_MISSION IS NULL OR @p_MISSION = '')
      AND (a.MISSION_DETAIL LIKE N'%' + @p_MISSION_DETAIL + N'%' OR @p_MISSION_DETAIL IS NULL OR @p_MISSION_DETAIL = '')
      AND (a.CAR_ID LIKE N'%' + @p_CAR_ID + N'%' OR @p_CAR_ID IS NULL OR @p_CAR_ID = '')
      AND (a.DRIVER_ID LIKE N'%' + @p_DRIVER_ID + N'%' OR @p_DRIVER_ID IS NULL OR @p_DRIVER_ID = '')
      AND (DATEDIFF(DAY,a.TIME_ARRIVE, CONVERT(DATETIME, @p_TIME_ARRIVE,103)) = 0 OR @p_TIME_ARRIVE IS NULL OR @p_TIME_ARRIVE = '')
      AND (a.LOCATION_ARRIVE LIKE N'%' + @p_LOCATION_ARRIVE + N'%' OR @p_LOCATION_ARRIVE IS NULL OR @p_LOCATION_ARRIVE = '')
      AND (a.EMPLOYEE_ID LIKE N'%' + @p_EMPLOYEE_ID + N'%' OR @p_EMPLOYEE_ID IS NULL OR @p_EMPLOYEE_ID = '')
      AND (a.RECORD_STATUS LIKE N'%' + @p_RECORD_STATUS + N'%' OR @p_RECORD_STATUS IS NULL OR @p_RECORD_STATUS = '')
      AND (a.AUTH_STATUS LIKE N'%' + @p_AUTH_STATUS + N'%' OR @p_AUTH_STATUS IS NULL OR @p_AUTH_STATUS = '')
      AND (a.MAKER_ID LIKE N'%' + @p_MAKER_ID + N'%' OR @p_MAKER_ID IS NULL OR @p_MAKER_ID = '')
      AND (DATEDIFF(DAY,a.CREATE_DT, CONVERT(DATETIME, @p_CREATE_DT,103)) = 0 OR @p_CREATE_DT IS NULL OR @p_CREATE_DT = '')
      AND (a.CHECKER_ID LIKE N'%' + @p_CHECKER_ID + N'%' OR @p_CHECKER_ID IS NULL OR @p_CHECKER_ID = '')
      AND (DATEDIFF(DAY,a.APPROVE_DT, CONVERT(DATETIME, @p_APPROVE_DT,103)) = 0 OR @p_APPROVE_DT IS NULL OR @p_APPROVE_DT = '')
      AND (a.APPROVER_ID LIKE N'%' + @p_APPROVER_ID + N'%' OR @p_APPROVER_ID IS NULL OR @p_APPROVER_ID = '')
      AND (a.BRANCH_ID LIKE N'%' + @p_BRANCH_ID + N'%' OR @p_BRANCH_ID IS NULL OR @p_BRANCH_ID = '')
      AND (a.MO_ID LIKE N'%' + @p_MO_ID + N'%' OR @p_MO_ID IS NULL OR @p_MO_ID = '')
      AND (a.DEP_ID LIKE N'%' + @p_DEP_ID + N'%' OR @p_DEP_ID IS NULL OR @p_DEP_ID = '')
      AND (a.DISPLAYEDID LIKE N'%' + @p_DISPLAYEDID + N'%' OR @p_DISPLAYEDID IS NULL OR @p_DISPLAYEDID = '')
      -- PAGING END
    ELSE
      -- PAGING BEGIN 
      SELECT TOP (@p_TOP) a.*
      -- SELECT END
      FROM ASSIGNMENT a WHERE 1 = 1
      AND (a.LOCATION LIKE N'%' + @p_LOCATION + N'%' OR @p_LOCATION IS NULL OR @p_LOCATION = '')
      AND (a.POSITION_ID LIKE N'%' + @p_POSITION_ID + N'%' OR @p_POSITION_ID IS NULL OR @p_POSITION_ID = '')
      AND (a.BROWSING_UNIT LIKE N'%' + @p_BROWSING_UNIT + N'%' OR @p_BROWSING_UNIT IS NULL OR @p_BROWSING_UNIT = '')
      AND (DATEDIFF(DAY,a.CREATE_DATE, CONVERT(DATETIME,@p_CREATE_DATE,103)) = 0 OR @p_CREATE_DATE IS NULL OR @p_CREATE_DATE = '')
      AND (DATEDIFF(DAY,a.FROM_DATE, CONVERT(DATETIME, @p_FROM_DATE,103)) = 0 OR @p_FROM_DATE IS NULL OR @p_FROM_DATE = '')
      AND (DATEDIFF(DAY,a.TO_DATE, CONVERT(DATETIME, @p_TO_DATE,103)) = 0 OR @p_TO_DATE IS NULL OR @p_TO_DATE = '')
      AND (a.MISSION LIKE N'%' + @p_MISSION + N'%' OR @p_MISSION IS NULL OR @p_MISSION = '')
      AND (a.MISSION_DETAIL LIKE N'%' + @p_MISSION_DETAIL + N'%' OR @p_MISSION_DETAIL IS NULL OR @p_MISSION_DETAIL = '')
      AND (a.CAR_ID LIKE N'%' + @p_CAR_ID + N'%' OR @p_CAR_ID IS NULL OR @p_CAR_ID = '')
      AND (a.DRIVER_ID LIKE N'%' + @p_DRIVER_ID + N'%' OR @p_DRIVER_ID IS NULL OR @p_DRIVER_ID = '')
      AND (DATEDIFF(DAY,a.TIME_ARRIVE, CONVERT(DATETIME, @p_TIME_ARRIVE,103)) = 0 OR @p_TIME_ARRIVE IS NULL OR @p_TIME_ARRIVE = '')
      AND (a.LOCATION_ARRIVE LIKE N'%' + @p_LOCATION_ARRIVE + N'%' OR @p_LOCATION_ARRIVE IS NULL OR @p_LOCATION_ARRIVE = '')
      AND (a.EMPLOYEE_ID LIKE N'%' + @p_EMPLOYEE_ID + N'%' OR @p_EMPLOYEE_ID IS NULL OR @p_EMPLOYEE_ID = '')
      AND (a.RECORD_STATUS LIKE N'%' + @p_RECORD_STATUS + N'%' OR @p_RECORD_STATUS IS NULL OR @p_RECORD_STATUS = '')
      AND (a.AUTH_STATUS LIKE N'%' + @p_AUTH_STATUS + N'%' OR @p_AUTH_STATUS IS NULL OR @p_AUTH_STATUS = '')
      AND (a.MAKER_ID LIKE N'%' + @p_MAKER_ID + N'%' OR @p_MAKER_ID IS NULL OR @p_MAKER_ID = '')
      AND (DATEDIFF(DAY,a.CREATE_DT, CONVERT(DATETIME, @p_CREATE_DT,103)) = 0 OR @p_CREATE_DT IS NULL OR @p_CREATE_DT = '')
      AND (a.CHECKER_ID LIKE N'%' + @p_CHECKER_ID + N'%' OR @p_CHECKER_ID IS NULL OR @p_CHECKER_ID = '')
      AND (DATEDIFF(DAY,a.APPROVE_DT, CONVERT(DATETIME, @p_APPROVE_DT,103)) = 0 OR @p_APPROVE_DT IS NULL OR @p_APPROVE_DT = '')
      AND (a.APPROVER_ID LIKE N'%' + @p_APPROVER_ID + N'%' OR @p_APPROVER_ID IS NULL OR @p_APPROVER_ID = '')
      AND (a.BRANCH_ID LIKE N'%' + @p_BRANCH_ID + N'%' OR @p_BRANCH_ID IS NULL OR @p_BRANCH_ID = '')
      AND (a.MO_ID LIKE N'%' + @p_MO_ID + N'%' OR @p_MO_ID IS NULL OR @p_MO_ID = '')
      AND (a.DEP_ID LIKE N'%' + @p_DEP_ID + N'%' OR @p_DEP_ID IS NULL OR @p_DEP_ID = '')
      AND (a.DISPLAYEDID LIKE N'%' + @p_DISPLAYEDID + N'%' OR @p_DISPLAYEDID IS NULL OR @p_DISPLAYEDID = '')
      -- PAGING END
  END -- PAGING
  --endregion
GO