USE gAMSCloud_DEMO_04
GO

IF DB_NAME() <> N'gAMSCloud_DEMO_04' SET NOEXEC ON
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create or alter procedure [dbo].[ASSIGNMENT_Upd]
--
GO
PRINT (N'Create or alter procedure [dbo].[ASSIGNMENT_Upd]')
GO
CREATE OR ALTER PROCEDURE dbo.ASSIGNMENT_Upd @p_DISPLAYEDID VARCHAR(9) = NULL,
@p_LOCATION NVARCHAR(200) = NULL,
@p_POSITION_ID NVARCHAR(15) = NULL,
@p_BROWSING_UNIT NVARCHAR(1) = NULL,
@p_CREATE_DATE VARCHAR(20) = NULL,
@p_FROM_DATE VARCHAR(20) = NULL,
@p_TO_DATE VARCHAR(20) = NULL,
@p_MISSION NVARCHAR(200) = NULL,
@p_MISSION_DETAIL NVARCHAR(200) = NULL,
@p_CAR_ID VARCHAR(15) = NULL,
@p_DRIVER_ID VARCHAR(15) = NULL,
@p_TIME_ARRIVE VARCHAR(20) = NULL,
@p_LOCATION_ARRIVE VARCHAR(15) = NULL,
@p_EMPLOYEE_ID VARCHAR(20) = NULL,
@p_RECORD_STATUS VARCHAR(1) = NULL,
@p_AUTH_STATUS VARCHAR(1) = NULL,
@p_MAKER_ID VARCHAR(15) = NULL,
@p_CREATE_DT VARCHAR(20) = NULL,
@p_CHECKER_ID VARCHAR(15) = NULL,
@p_APPROVE_DT VARCHAR(20) = NULL,
@p_APPROVER_ID VARCHAR(15) = NULL,
@p_BRANCH_ID VARCHAR(15) = NULL,
@p_MO_ID VARCHAR(15) = NULL,
@p_DEP_ID VARCHAR(15) = NULL

AS 
DECLARE @ERRORSYS NVARCHAR(15) = ''
IF (NOT EXISTS (SELECT * FROM ASSIGNMENT a WHERE a.DisplayedID = @p_DISPLAYEDID))
  SET @ERRORSYS = 'NOT FOUND'

IF @ERRORSYS <> ''
BEGIN
	SELECT ErrorCode Result, ErrorDesc ErrorDesc FROM SYS_ERROR WHERE ErrorCode = @ERRORSYS
  RETURN '0'
END

  DECLARE  @p_INYEAR_ID INT = -1;
  IF (SELECT MAX(INYEAR_ID) FROM ASSIGNMENT WHERE YEAR(CREATE_DATE) = YEAR(CONVERT(DATETIME, @p_CREATE_DATE,103))) IS NOT NULL
  SET @p_INYEAR_ID =  (SELECT MAX(INYEAR_ID) FROM ASSIGNMENT WHERE YEAR(CREATE_DATE) = YEAR(CONVERT(DATETIME, @p_CREATE_DATE,103))) + 1;
  ELSE SET @p_INYEAR_ID = 0;

BEGIN TRANSACTION
BEGIN
  UPDATE ASSIGNMENT
  SET LOCATION = @p_LOCATION, POSITION_ID = @p_POSITION_ID, BROWSING_UNIT = @p_BROWSING_UNIT, CREATE_DATE = CONVERT(DATETIME, @p_CREATE_DATE,103), FROM_DATE = CONVERT(DATETIME, @p_FROM_DATE,103), TO_DATE = CONVERT(DATETIME, @p_TO_DATE,103), MISSION = @p_MISSION,
  MISSION_DETAIL = @p_MISSION_DETAIL, CAR_ID = @p_CAR_ID, DRIVER_ID = @p_DRIVER_ID, TIME_ARRIVE = CONVERT(DATETIME, @p_TIME_ARRIVE,103), LOCATION_ARRIVE = @p_LOCATION_ARRIVE, EMPLOYEE_ID = @p_EMPLOYEE_ID,
  RECORD_STATUS = @p_RECORD_STATUS, AUTH_STATUS = @p_AUTH_STATUS, MAKER_ID = @p_MAKER_ID, CREATE_DT = CONVERT(DATETIME, @p_CREATE_DT,103), APPROVE_DT = CONVERT(DATETIME, @p_APPROVE_DT,103),
  APPROVER_ID = @p_APPROVER_ID, BRANCH_ID = @p_BRANCH_ID, MO_ID = @p_MO_ID, DEP_ID = @p_DEP_ID, INYEAR_ID = @p_INYEAR_ID
  WHERE DisplayedID = @p_DISPLAYEDID
END
IF @@Error <> 0 GOTO ABORT
COMMIT TRANSACTION


SELECT '0' AS Result, '' ErrorDesc
RETURN '0'

ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT '-1' AS Result, '' ErrorDesc
    RETURN '-1'
  END

GO