USE gAMSCloud_DEMO_04
GO

IF DB_NAME() <> N'gAMSCloud_DEMO_04' SET NOEXEC ON
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create or alter procedure [dbo].[ASSIGNMENT_DEL]
--
GO
PRINT (N'Create or alter procedure [dbo].[ASSIGNMENT_DEL]')
GO
CREATE OR ALTER PROCEDURE dbo.ASSIGNMENT_DEL @p_DISPLAYEDID VARCHAR(9) = NULL
AS 
DECLARE @ERRORSYS NVARCHAR(15) = ''
IF (NOT EXISTS (SELECT * FROM ASSIGNMENT a WHERE a.DisplayedID = @p_DISPLAYEDID))
  SET @ERRORSYS = 'NOT FOUND'

IF @ERRORSYS <> ''
BEGIN
	SELECT ErrorCode Result, ErrorDesc ErrorDesc FROM SYS_ERROR WHERE ErrorCode = @ERRORSYS
  RETURN '0'
END

BEGIN TRANSACTION
BEGIN
  DELETE FROM ASSIGNMENT WHERE DisplayedID = @p_DISPLAYEDID
  IF @@error <> 0
  GOTO ABORT
END
COMMIT TRANSACTION

SELECT '0' AS Result, '' ErrorDesc
RETURN '0'

ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT '-1' AS Result, '' ErrorDesc
    RETURN '-1'
  END

GO