USE gAMSCloud_DEMO_04
GO

IF DB_NAME() <> N'gAMSCloud_DEMO_04' SET NOEXEC ON
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create procedure [dbo].[EMPLOYEEE_DEL]
--
GO
PRINT (N'Create procedure [dbo].[EMPLOYEEE_DEL]')
GO
CREATE PROCEDURE dbo.EMPLOYEEE_DEL
@p_DISPLAYEDID NVARCHAR(20) = NULL

AS

DECLARE @ERRORSYS NVARCHAR(15) = ''
IF (NOT EXISTS (SELECT * FROM EMPLOYEEE e WHERE DisplayedID = @p_DISPLAYEDID))
  SET @ERRORSYS = 'NOT FOUND'

IF @ERRORSYS <> ''
BEGIN
	SELECT ErrorCode Result, ErrorDesc ErrorDesc FROM SYS_ERROR WHERE ErrorCode = @ERRORSYS
  RETURN '0'
END

  BEGIN TRANSACTION
  DELETE FROM EMPLOYEEE
  WHERE DisplayedID = @p_DISPLAYEDID
  
  COMMIT TRANSACTION

  SELECT
  '0' AS RESULT, IDENT_CURRENT('EMPLOYEEE') ID
  RETURN '0'

ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT
      '-1' AS Result
     ,'' ID
    RETURN '-1'
  END
GO