USE gAMSCloud_DEMO_04
GO

IF DB_NAME() <> N'gAMSCloud_DEMO_04' SET NOEXEC ON
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create or alter procedure [dbo].[TRIP_INS]
--
GO
PRINT (N'Create or alter procedure [dbo].[TRIP_INS]')
GO
 CREATE OR ALTER PROCEDURE dbo.TRIP_INS
@p_AS_ID NVARCHAR(20) = NULL,
@p_TYPE VARCHAR(1) = NULL,
@p_QUANTITY DECIMAL(18,2) = NULL,
@p_QUANTITY_UNIT NVARCHAR(20) = NULL,
@p_QUANTITY_TRIP int = NULL,
@p_GO_FROM NVARCHAR(200) = NULL,
@p_GO_TO NVARCHAR(200) = NULL,
@p_TIME VARCHAR(20) = NULL,
@p_LENGTH DECIMAL(18,2) = NULL,
@p_LENGTH_UNIT NVARCHAR(20) = NULL 

AS
  BEGIN TRANSACTION
  INSERT INTO TRIP([AS_ID],[TYPE],[QUANTITY],[QUANTITY_UNIT],[QUANTITY_TRIP],[GO_FROM],[GO_TO],[TIME],[LENGTH],[LENGTH_UNIT])
  VALUES (@p_AS_ID,@p_TYPE,@p_QUANTITY,@p_QUANTITY_UNIT,@p_QUANTITY_TRIP,@p_GO_FROM,@p_GO_TO,@p_TIME,@p_LENGTH,@p_LENGTH_UNIT)
 
  COMMIT TRANSACTION

  SELECT
  '0' AS RESULT, @p_AS_ID AS_ID
  RETURN '0'

ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT
      '-1' AS Result
     ,'' AS_ID
    RETURN '-1'
  END
GO