USE gAMSCloud_DEMO_04
GO

IF DB_NAME() <> N'gAMSCloud_DEMO_04' SET NOEXEC ON
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create or alter procedure [dbo].[TRIP_DeL]
--
GO
PRINT (N'Create or alter procedure [dbo].[TRIP_DeL]')
GO
 CREATE OR ALTER PROCEDURE dbo.TRIP_DeL
@p_AS_ID NVARCHAR(20) = NULL,
@p_TYPE VARCHAR(1) = NULL

AS
DECLARE @ERRORSYS NVARCHAR(15) = ''
IF (NOT EXISTS (SELECT * FROM TRIP t WHERE t.AS_ID= @p_AS_ID AND t.TYPE = @p_TYPE))
  SET @ERRORSYS = 'NOT FOUND'

IF @ERRORSYS <> ''
BEGIN
	SELECT ErrorCode Result, ErrorDesc ErrorDesc FROM SYS_ERROR WHERE ErrorCode = @ERRORSYS
  RETURN '0'
END
  BEGIN TRANSACTION
    DELETE FROM TRIP WHERE (AS_ID = @p_AS_ID AND TYPE = @p_TYPE)  
  COMMIT TRANSACTION

  SELECT
  '0' AS RESULT, @p_AS_ID AS_ID
  RETURN '0'

ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT
      '-1' AS Result
     ,'' AS_ID
    RETURN '-1'
  END
GO