USE gAMSCloud_DEMO_04
GO

IF DB_NAME() <> N'gAMSCloud_DEMO_04' SET NOEXEC ON
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create or alter procedure [dbo].[TRIP_Search]
--
GO
PRINT (N'Create or alter procedure [dbo].[TRIP_Search]')
GO
 CREATE OR ALTER PROCEDURE dbo.TRIP_Search @p_TOP INT = 500,
@p_AS_ID NVARCHAR(20) = NULL,
@p_TYPE VARCHAR(1) = NULL,
@p_QUANTITY DECIMAL(18,2) = NULL,
@p_QUANTITY_UNIT NVARCHAR(20) = NULL,
@p_QUANTITY_TRIP INT = NULL,
@p_GO_FROM NVARCHAR(200) = NULL,
@p_GO_TO NVARCHAR(200) = NULL,
@p_TIME VARCHAR(20) = NULL,
@p_LENGTH DECIMAL(18,2) = NULL,
@p_LENGTH_UNIT NVARCHAR(20) = NULL 

AS
  BEGIN -- PAGING
    IF (@p_TOP IS NULL OR @p_TOP = '' OR @p_TOP = 0) -- PAGING BEGIN
      SELECT t.*
      -- SELECT END
      FROM TRIP t WHERE 1 = 1 
      AND (t.AS_ID = @p_AS_ID OR @p_AS_ID IS NULL OR @p_AS_ID = '')
      AND (t.TYPE = @p_TYPE OR @p_TYPE IS NULL OR @p_TYPE = '')
      AND (t.QUANTITY = @p_QUANTITY OR @p_QUANTITY IS NULL OR @p_QUANTITY <= 0)
      AND (t.QUANTITY_UNIT = @p_QUANTITY_UNIT OR @p_QUANTITY_UNIT IS NULL OR @p_QUANTITY_UNIT = '')
      AND (t.QUANTITY_TRIP = @p_QUANTITY_TRIP OR @p_QUANTITY_TRIP IS NULL OR @p_QUANTITY_TRIP = '')
      AND (t.GO_FROM = @p_GO_FROM OR @p_GO_FROM IS NULL OR @p_GO_FROM = '')
      AND (t.GO_TO = @p_GO_TO OR @p_GO_TO IS NULL OR @p_GO_TO = '')
      AND (DATEDIFF(DAY,t.TIME, CONVERT(DATETIME,@p_TIME,103)) = 0 OR @p_TIME IS NULL OR @p_TIME = '')
      AND (t.LENGTH = @p_LENGTH OR @p_LENGTH IS NULL OR @p_LENGTH <= 0)
      AND (t.LENGTH_UNIT = @p_LENGTH_UNIT OR @p_LENGTH_UNIT IS NULL OR @p_LENGTH_UNIT = '')
      -- PAGING END
    ELSE
      -- PAGING BEGIN 
      SELECT TOP (@p_TOP) t.* 
      -- SELECT END
      FROM TRIP t WHERE 1 = 1 
      AND (t.AS_ID = @p_AS_ID OR @p_AS_ID IS NULL OR @p_AS_ID = '')
      AND (t.TYPE = @p_TYPE OR @p_TYPE IS NULL OR @p_TYPE = '')
      AND (t.QUANTITY = @p_QUANTITY OR @p_QUANTITY IS NULL OR @p_QUANTITY <= 0)
      AND (t.QUANTITY_UNIT = @p_QUANTITY_UNIT OR @p_QUANTITY_UNIT IS NULL OR @p_QUANTITY_UNIT = '')
      AND (t.QUANTITY_TRIP = @p_QUANTITY_TRIP OR @p_QUANTITY_TRIP IS NULL OR @p_QUANTITY_TRIP = '')
      AND (t.GO_FROM = @p_GO_FROM OR @p_GO_FROM IS NULL OR @p_GO_FROM = '')
      AND (t.GO_TO = @p_GO_TO OR @p_GO_TO IS NULL OR @p_GO_TO = '')
      AND (DATEDIFF(DAY,t.TIME, CONVERT(DATETIME,@p_TIME,103)) = 0 OR @p_TIME IS NULL OR @p_TIME = '')
      AND (t.LENGTH = @p_LENGTH OR @p_LENGTH IS NULL OR @p_LENGTH <= 0)
      AND (t.LENGTH_UNIT = @p_LENGTH_UNIT OR @p_LENGTH_UNIT IS NULL OR @p_LENGTH_UNIT = '')
      -- PAGING END
  END -- PAGING
GO