USE gAMSCloud_DEMO_04
GO

IF DB_NAME() <> N'gAMSCloud_DEMO_04' SET NOEXEC ON
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create or alter procedure [dbo].[VEHICLE_Del]
--
GO
PRINT (N'Create or alter procedure [dbo].[VEHICLE_Del]')
GO
CREATE OR ALTER PROCEDURE dbo.VEHICLE_Del
@p_CAR_ID VARCHAR(20) = NULL

AS

DECLARE @ERRORSYS NVARCHAR(15) = ''
IF (NOT EXISTS (SELECT * FROM VEHICLE v WHERE v.CAR_ID = @p_CAR_ID))
  SET @ERRORSYS = 'NOT FOUND'

IF @ERRORSYS <> ''
BEGIN
	SELECT ErrorCode Result, ErrorDesc ErrorDesc FROM SYS_ERROR WHERE ErrorCode = @ERRORSYS
  RETURN '0'
END

  BEGIN TRANSACTION
  DELETE FROM VEHICLE WHERE CAR_ID = @p_CAR_ID
 
  COMMIT TRANSACTION

  SELECT
  '0' AS RESULT, @p_CAR_ID CAR_ID
  RETURN '0'

ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT
      '-1' AS Result
     ,'' CAR_ID
    RETURN '-1'
  END
GO