USE gAMSCloud_DEMO_04
GO

IF DB_NAME() <> N'gAMSCloud_DEMO_04' SET NOEXEC ON
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

--
-- Create or alter procedure [dbo].[VEHICLE_Upd]
--
GO
PRINT (N'Create or alter procedure [dbo].[VEHICLE_Upd]')
GO
CREATE OR ALTER PROCEDURE dbo.VEHICLE_Upd
@p_CAR_ID VARCHAR(20) = NULL,
@p_TYPE NVARCHAR(200) = NULL,
@p_NAME NVARCHAR(200) = NULL,
@p_OG_COUNTRY NVARCHAR(200) = NULL,
@p_BRAND NVARCHAR(200) = NULL,
@p_MANAGING_UNIT NVARCHAR(200) = NULL,
@p_FUEL NVARCHAR(200) = NULL,
@p_CONSUMPTION DECIMAL(18,2) = NULL

AS

DECLARE @ERRORSYS NVARCHAR(15) = ''
IF (NOT EXISTS (SELECT * FROM VEHICLE v WHERE v.CAR_ID = @p_CAR_ID))
  SET @ERRORSYS = 'NOT FOUND'

IF @ERRORSYS <> ''
BEGIN
	SELECT ErrorCode Result, ErrorDesc ErrorDesc FROM SYS_ERROR WHERE ErrorCode = @ERRORSYS
  RETURN '0'
END

  BEGIN TRANSACTION
  UPDATE VEHICLE SET [TYPE] = @p_TYPE,[NAME] = @p_NAME,[OG_COUNTRY] = @p_OG_COUNTRY,[BRAND] = @p_BRAND,[MANAGING_UNIT] = @p_MANAGING_UNIT,[FUEL] = @p_FUEL,[CONSUMPTION] = @p_CONSUMPTION
  WHERE CAR_ID = @p_CAR_ID
 IF @@Error <> 0 GOTO ABORT
  COMMIT TRANSACTION

  SELECT
  '0' AS RESULT, @p_CAR_ID CAR_ID
  RETURN '0'

ABORT:
  BEGIN
    ROLLBACK TRANSACTION
    SELECT
      '-1' AS Result
     ,'' CAR_ID
    RETURN '-1'
  END
GO